//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREPSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesData
    {
        public int Sales_ID { get; set; }
        public string Product_Name { get; set; }
        public int Amount_Sold { get; set; }
        public string Date_Sold { get; set; }
        public string Time_Sold { get; set; }
        public decimal Price { get; set; }
    }
}
