//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREPSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesData
    {
        public string Sales_ID { get; set; }
        public string Product_ID { get; set; }
        public Nullable<int> Amount_Sold { get; set; }
        public Nullable<System.DateTime> Date_Sold { get; set; }
        public Nullable<System.TimeSpan> Time_Sold { get; set; }
    
        public virtual StockData StockData { get; set; }
    }
}
