//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SREPSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockData()
        {
            this.SalesDatas = new HashSet<SalesData>();
        }
    
        public string Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Stock_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesData> SalesDatas { get; set; }
    }
}
